effects: 
  - POISON:50:1
  - SLOW:200:2
  - CONFUSION:100:1
  - BLINDNESS:200:1
  - WEAKNESS:100:1
max-duration: 1000
messages:
  stepped-on: "You stepped on a { effect } PotatoBomb!"
  dropped: "You dropped a { effect } PotatoBomb!"