allow-crafting:
  poisonous-potatoes: false

effect-durations:
  confusion: 100
  blindness: 100
  poison: 20
  slow: 200
  harm: 40
  hunger: 100
  weakness: 200
  wither: 100
  slowdigging: 100
  
messages:
  stepped-on: "You stepped on a { effect } PotatoBomb!"
  dropped: "You dropped a { effect } PotatoBomb!"