name: PotatoBombs
main: com.norcode.bukkit.potatobombs.PotatoBombs
version: 0.0.2
commands:
  potatobombs:
    aliases: [pbomb, pbombs, pb]
    description: potato bomb config
    permission: potatobombs.admin